openapi: 3.0.1
info:
  title: Spring RestDocs to Redoc
  description: Spring RestDocs를 Redoc문서로 변환한다.
  version: 0.0.1
servers:
- url: http://localhost:9090
tags: []
paths:
  /api/product/list:
    get:
      tags:
      - Product
      summary: 상품 목록 조회
      description: 상품 목록 조회
      operationId: get-products
      parameters:
      - name: subcategoryId
        in: query
        description: 서브 카테고리 고유 아이디
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: 인증 토큰
        required: true
        schema:
          type: string
        example: "Bearer {accessToken}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-product-list1653264513'
              examples:
                get-products:
                  value: "{\"resultCode\":\"200\",\"msg\":\"OK\",\"data\":{\"list\"\
                    :[{\"id\":1,\"categoryCode\":\"PRODUCT_BEVERAGE\",\"categoryName\"\
                    :\"Beverage\",\"subCategoryCode\":\"COFFEE\",\"subCategoryName\"\
                    :\"Coffee\",\"productCode\":\"COF001\",\"productName\":\"Americano\"\
                    ,\"price\":4000,\"paymentType\":\"NORMAL\"},{\"id\":2,\"categoryCode\"\
                    :\"PRODUCT_BEVERAGE\",\"categoryName\":\"Beverage\",\"subCategoryCode\"\
                    :\"COFFEE\",\"subCategoryName\":\"Coffee\",\"productCode\":\"\
                    COF002\",\"productName\":\"Cafe Latte\",\"price\":4500,\"paymentType\"\
                    :\"NORMAL\"},{\"id\":3,\"categoryCode\":\"PRODUCT_BEVERAGE\",\"\
                    categoryName\":\"Beverage\",\"subCategoryCode\":\"COFFEE\",\"\
                    subCategoryName\":\"Coffee\",\"productCode\":\"COF003\",\"productName\"\
                    :\"Cappuccino\",\"price\":4800,\"paymentType\":\"NORMAL\"},{\"\
                    id\":4,\"categoryCode\":\"PRODUCT_BEVERAGE\",\"categoryName\"\
                    :\"Beverage\",\"subCategoryCode\":\"COFFEE\",\"subCategoryName\"\
                    :\"Coffee\",\"productCode\":\"COF004\",\"productName\":\"Espresso\"\
                    ,\"price\":3500,\"paymentType\":\"NORMAL\"},{\"id\":5,\"categoryCode\"\
                    :\"PRODUCT_BEVERAGE\",\"categoryName\":\"Beverage\",\"subCategoryCode\"\
                    :\"COFFEE\",\"subCategoryName\":\"Coffee\",\"productCode\":\"\
                    COF005\",\"productName\":\"Vanilla Latte\",\"price\":5000,\"paymentType\"\
                    :\"NORMAL\"},{\"id\":6,\"categoryCode\":\"PRODUCT_BEVERAGE\",\"\
                    categoryName\":\"Beverage\",\"subCategoryCode\":\"COFFEE\",\"\
                    subCategoryName\":\"Coffee\",\"productCode\":\"COF006\",\"productName\"\
                    :\"Mocha\",\"price\":5200,\"paymentType\":\"NORMAL\"}]},\"timeZone\"\
                    :\"Asia/Seoul\",\"timeStamp\":1751469799808,\"languageCode\":\"\
                    ko\"}"
components:
  schemas:
    api-product-list1653264513:
      required:
      - languageCode
      - msg
      - resultCode
      - timeStamp
      - timeZone
      type: object
      properties:
        timeStamp:
          type: number
          description: 서버 응답시간
        msg:
          type: string
          description: 결과 메시지
        data:
          required:
          - list
          type: object
          properties:
            list:
              type: array
              description: 상품 목록
              items:
                required:
                - categoryCode
                - categoryName
                - id
                - paymentType
                - price
                - productCode
                - productName
                - subCategoryCode
                - subCategoryName
                type: object
                properties:
                  productCode:
                    type: string
                    description: 상품코드
                  price:
                    type: number
                    description: 상품 가격
                  subCategoryCode:
                    type: string
                    description: 서브 카테고리 코드
                  categoryCode:
                    type: string
                    description: 카테고리 코드
                  id:
                    type: number
                    description: 상품 ID
                  categoryName:
                    type: string
                    description: 카테고리명
                  productName:
                    type: string
                    description: 상품명
                  paymentType:
                    type: string
                    description: 결제 타입
                  subCategoryName:
                    type: string
                    description: 서브 카테고리명
        resultCode:
          type: string
          description: 결과 코드
        timeZone:
          type: string
          description: 서버 타임존
        languageCode:
          type: string
          description: 응답의 언어셋
